name: LaTeX CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  latex-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full latexmk chktex hunspell curl

      - name: Compile LaTeX
        run: |
          latexmk -pdf -interaction=nonstopmode -quiet main.tex

      - name: Check for Undefined References
        run: |
          latexmk -pdf -interaction=nonstopmode -quiet main.tex
          grep "undefined" main.log || echo "No undefined references found"

      - name: Validate Bibliography
        run: |
          bibtex main.aux
          grep "Warning--I didn't find a database entry" main.blg && exit 1 || echo "All citations found."

      - name: Run LaTeX Linter (chktex)
        run: |
          chktex -v main.tex

      - name: Check for Broken Links
        run: |
          grep -oP '(?<=\\href{)[^}]+' main.tex | while read -r url; do
            curl --output /dev/null --silent --head --fail "$url" || echo "Broken URL: $url"
          done

      - name: Check for TODOs and FIXMEs
        run: |
          grep -rnw . -e 'TODO' -e 'FIXME' --include=\*.tex && exit 1 || echo "No TODOs found."

      - name: Check for Extra Spaces or Empty Lines
        run: |
          grep -n "  " *.tex || echo "No extra spaces found"
          grep -n "^$" *.tex || echo "No unnecessary empty lines"

      - name: Check for Missing Figures
        run: |
          grep -oP '(?<=\\includegraphics{)[^}]+' main.tex | while read -r file; do
            if [ ! -f "$file" ]; then echo "Missing image: $file"; exit 1; fi
          done

      - name: Check for Consistent File Naming
        run: |
          find . -name "*.tex" | grep -E '[A-Z]' && echo "Inconsistent file naming" && exit 1 || echo "All filenames lowercase."
