name: Static file check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  staticcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install codespell
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell curl

      - name: Run codespell on md files
        run: |
          codespell '**/*.md'  # You can add more custom ignores here

      - name: Check for Broken Links
        run: |
          grep -oP '(?<=\\href{)[^}]+' main.md | while read -r url; do
            curl --output /dev/null --silent --head --fail "$url" || echo "Broken URL: $url"
          done

      - name: Check for TODOs and FIXMEs
        run: |
          grep -rnw . -e 'TODO' -e 'FIXME' --include=\*.md && exit 1 || echo "No TODOs found."
